[package]
name = "ahead-binding"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
ahead-core = { path = "../../crates/core" }
ahead-client = { path = "../../crates/client" }
ahead-sqlite = { path = "../../crates/sqlite" }
serde_json.workspace = true
[dev-dependencies]
tempfile.workspace = true
