use serde_json::Value;
use std::fmt::Write;
fn arr<'a>(v: &'a Value, k: &str) -> &'a Vec<Value> {
    v[k].as_array().unwrap()
}
fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v[k].as_str().unwrap()
}
fn lower(s: &str) -> String {
    let mut c = s.chars();
    format!("{}{}", c.next().unwrap().to_lowercase(), c.as_str())
}
fn ty(t: &Value, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = ty(&t["element"], dart);
        return if dart {
            format!("List<{e}>")
        } else {
            format!("{e}[]")
        };
    }
    if t["kind"] == "enum" {
        return s(t, "name").into();
    }
    match s(t, "name") {
        "boolean" => {
            if dart {
                "bool"
            } else {
                "boolean"
            }
        }
        "int" => {
            if dart {
                "int"
            } else {
                "number"
            }
        }
        "float" => {
            if dart {
                "double"
            } else {
                "number"
            }
        }
        "dateTime" => {
            if dart {
                "DateTime"
            } else {
                "Date"
            }
        }
        _ => {
            if dart {
                "String"
            } else {
                "string"
            }
        }
    }
    .into()
}
fn ft(f: &Value, dart: bool) -> String {
    format!(
        "{}{}",
        ty(&f["type"], dart),
        if f["nullable"] == true {
            if dart { "?" } else { " | null" }
        } else {
            ""
        }
    )
}
fn decode(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = decode(&t["element"], "e", dart);
        return if dart {
            format!("({x} as List).map((e) => {e}).toList()")
        } else {
            format!("({x} as unknown[]).map(e => {e})")
        };
    }
    if t["kind"] == "enum" {
        let n = s(t, "name");
        return if dart {
            format!("{n}.values.byName({x} as String)")
        } else {
            format!("{x} as {n}")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("DateTime.parse({x} as String)")
        } else {
            format!("new Date({x} as string)")
        };
    }
    if dart && t["name"] == "float" {
        format!("({x} as num).toDouble()")
    } else {
        format!("{x} as {}", ty(t, dart))
    }
}
fn encoded(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = encoded(&t["element"], "e", dart);
        return if dart {
            format!("{x}.map((e) => {e}).toList()")
        } else {
            format!("{x}.map(e => {e})")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("{x}.toUtc().toIso8601String()")
        } else {
            format!("{x}.toISOString()")
        };
    }
    if dart && t["kind"] == "enum" {
        format!("{x}.name")
    } else {
        x.into()
    }
}
fn enc(f: &Value, x: &str, dart: bool) -> String {
    let e = encoded(
        &f["type"],
        &if dart && f["nullable"] == true {
            format!("{x}!")
        } else {
            x.into()
        },
        dart,
    );
    if f["nullable"] == true {
        format!("{x} == null ? null : {e}")
    } else {
        e
    }
}
pub fn typescript(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by otter-sync. Do not edit.\nexport interface ClientPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; query(model:string,where?:Record<string,unknown>):Promise<Record<string,unknown>[]>; mutate(value:object):Promise<number>; querySpec?(model:string,query:object):Promise<Record<string,unknown>[]>; related?(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing?(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }\n",
    );
    writeln!(o, "export const schema = {} as const;", v["schema"]).unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "export type {} = {};",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for (suffix, filter, partial) in
            [("", 0, false), ("Identity", 1, false), ("Patch", 2, true)]
        {
            writeln!(o, "export interface {n}{suffix} {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (filter == 1 && !id) || (filter == 2 && id) {
                    continue;
                }
                writeln!(
                    o,
                    " {}{}: {};",
                    s(f, "name"),
                    if partial { "?" } else { "" },
                    ft(f, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
        writeln!(
            o,
            "export function decode{n}(row:Record<string,unknown>):{n} {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            let k = s(f, "name");
            let x = format!("row.{k}");
            let dec = decode(&f["type"], &x, false);
            writeln!(
                o,
                " {k}: {},",
                if f["nullable"] == true {
                    format!("{x} == null ? null : {dec}")
                } else {
                    dec
                }
            )
            .unwrap();
        }
        o.push_str("}; }\n");
        for (suffix, partial) in [
            ("", false),
            ("Identity", false),
            ("Patch", true),
            ("Where", true),
        ] {
            let input = if suffix == "Where" {
                format!("Partial<{n}>")
            } else {
                format!("{n}{suffix}")
            };
            writeln!(o,"export function encode{n}{suffix}(value:{input}):Record<string,unknown> {{ return {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (suffix == "Identity" && !id) || (suffix == "Patch" && id) {
                    continue;
                }
                let k = s(f, "name");
                let ex = enc(f, &format!("value.{k}"), false);
                if partial {
                    writeln!(o, " ...(value.{k} !== undefined ? {{ {k}: {ex} }} : {{}}),").unwrap()
                } else {
                    writeln!(o, " {k}: {ex},").unwrap()
                }
            }
            o.push_str("}; }\n");
        }
    }
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(o, "export interface {n}Args {{").unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let input = match s(slot, "operation") {
                "create" => model.to_string(),
                "delete" => format!("{model}Identity"),
                _ => {
                    let patch = if let Some(a) = slot["allowedPatchFields"].as_array() {
                        format!(
                            "Pick<{model}Patch, {}>",
                            if a.is_empty() {
                                "never".into()
                            } else {
                                a.iter()
                                    .map(Value::to_string)
                                    .collect::<Vec<_>>()
                                    .join(" | ")
                            }
                        )
                    } else {
                        format!("{model}Patch")
                    };
                    format!("{{ identity:{model}Identity; values:{patch} }}")
                }
            };
            let card = s(slot, "cardinality");
            writeln!(
                o,
                " {}{}: {}{};",
                s(slot, "name"),
                if card == "optional" { "?" } else { "" },
                input,
                if card == "list" { "[]" } else { "" }
            )
            .unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "export function {n}(args:{n}Args) {{ const operations:object[] = [];"
        )
        .unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            writeln!(
                o,
                " for (const value of {}) {{",
                if card == "list" {
                    format!("args.{key}")
                } else if card == "optional" {
                    format!("args.{key} === undefined ? [] : [args.{key}]")
                } else {
                    format!("[args.{key}]")
                }
            )
            .unwrap();
            let id = if op == "update" {
                "value.identity"
            } else {
                "value"
            };
            let vals = if op == "delete" {
                String::new()
            } else if op == "update" {
                format!(", values:encode{model}Patch(value.values)")
            } else {
                format!(", values:encode{model}Patch(value)")
            };
            writeln!(o," operations.push({{ model:'{model}', op:'{op}', identity:encode{model}Identity({id}){vals} }}); }}").unwrap();
        }
        writeln!(
            o,
            " return {{name:'{n}',version:{},operations}}; }}",
            mu["version"]
        )
        .unwrap();
    }
    o.push_str("export class GeneratedClient { readonly client:ClientPort; constructor(client:ClientPort) { this.client=client; }\n");
    ts_queries(v, &mut o);
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        let name = lower(n);
        let lists = arr(m, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "list")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let where_type = if lists.is_empty() {
            format!("Partial<{n}>")
        } else {
            format!("Partial<Omit<{n}, {lists}>>")
        };
        writeln!(o," async read{n}(identity:{n}Identity):Promise<{n}|null> {{ const row=await this.client.read('{n}',encode{n}Identity(identity)); return row===null ? null : decode{n}(row); }}\n async {name}(where:{where_type}={{}}):Promise<{n}[]> {{ return (await this.client.query('{n}',encode{n}Where(where))).map(decode{n}); }}").unwrap();
    }
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(
            o,
            " {}(args:{n}Args):Promise<number> {{ return this.client.mutate({n}(args)); }}",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\n");
    o
}
fn slot_input_type(slot: &Value) -> String {
    let model = s(slot, "model");
    let one = match s(slot, "operation") {
        "create" => model.to_string(),
        "delete" => format!("{{ identity: {model}Identity }}"),
        _ => {
            let patch = match slot["allowedPatchFields"].as_array() {
                Some(a) if a.is_empty() => format!("Pick<{model}Patch, never>"),
                Some(a) => format!(
                    "Pick<{model}Patch, {}>",
                    a.iter()
                        .map(Value::to_string)
                        .collect::<Vec<_>>()
                        .join(" | ")
                ),
                None => format!("{model}Patch"),
            };
            format!("{{ identity: {model}Identity; patch: {patch} }}")
        }
    };
    match s(slot, "cardinality") {
        "list" => format!("{one}[]"),
        "optional" => format!("{one} | null"),
        _ => one,
    }
}
/// Backend surface bound to the compiled schema. `runtime` is the import specifier of `@ottersync/server`.
pub fn backend_typescript(v: &Value, runtime: &str) -> String {
    let mut o = String::from("// Generated by otter-sync. Do not edit.\n");
    writeln!(o, "import {{ createBackend as createRuntimeBackend, type BackendOptions, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ MutationRejected, devAuth, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    let models = arr(&v["schema"], "models");
    let names: Vec<String> = models
        .iter()
        .flat_map(|m| {
            let n = s(m, "name");
            [
                format!("{n} as {n}Record"),
                format!("{n}Identity"),
                format!("{n}Patch"),
            ]
        })
        .collect();
    writeln!(
        o,
        "import type {{ {} }} from \"./generated.ts\";",
        names.join(", ")
    )
    .unwrap();
    for m in models {
        let n = s(m, "name");
        writeln!(o, "export type {n} = {n}Record;").unwrap();
        writeln!(o, "export type {{ {n}Identity, {n}Patch }};").unwrap();
        writeln!(o, "export function {n}(identity: {n}Identity): RecordRef {{ return {{ model: \"{n}\", identity }}; }}").unwrap();
    }
    let mut backend = v.clone();
    if let Some(history) = v.get("backendMutations") {
        backend["mutations"] = history.clone();
        backend.as_object_mut().unwrap().remove("backendMutations");
    }
    writeln!(o, "export const schema = {} as const;", backend).unwrap();
    let mutations = arr(&backend, "mutations");
    let latest = |name: &str| {
        mutations
            .iter()
            .filter(|m| s(m, "name") == name)
            .map(|m| m["version"].as_u64().unwrap())
            .max()
            .unwrap()
    };
    let key = |m: &Value| {
        let n = s(m, "name");
        let ver = m["version"].as_u64().unwrap();
        if ver == latest(n) {
            lower(n)
        } else {
            format!("{}V{ver}", lower(n))
        }
    };
    let input_name = |m: &Value| {
        let n = s(m, "name");
        let ver = m["version"].as_u64().unwrap();
        if ver == latest(n) {
            format!("{n}Input")
        } else {
            format!("{n}V{ver}Input")
        }
    };
    for m in mutations {
        writeln!(o, "export interface {} {{", input_name(m)).unwrap();
        for slot in arr(m, "slots") {
            writeln!(o, " {}: {};", s(slot, "name"), slot_input_type(slot)).unwrap();
        }
        o.push_str("}\n");
    }
    o.push_str("export interface Handlers<Tx> {\n");
    for m in mutations {
        writeln!(
            o,
            " {}(call: HandlerCall<Tx, {}>): Promise<void | {{ channel: string }}>;",
            key(m),
            input_name(m)
        )
        .unwrap();
    }
    o.push_str("}\n");
    o.push_str("export interface Loaders<Tx> {\n");
    for m in models {
        let n = s(m, "name");
        writeln!(
            o,
            " {}(call: LoaderCall<Tx, {n}Identity>): Promise<readonly ({n} | null)[]>;",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\n");
    o.push_str("export type Options<Tx> = Omit<BackendOptions<Tx>, \"config\" | \"handlers\" | \"loaders\"> & { handlers: Handlers<Tx>; loaders: Loaders<Tx> };\n");
    o.push_str("export function createBackend<Tx>(options: Options<Tx>) {\n return createRuntimeBackend<Tx>({ ...options, config: schema, handlers: options.handlers as unknown as BackendOptions<Tx>[\"handlers\"], loaders: options.loaders as unknown as BackendOptions<Tx>[\"loaders\"] });\n}\n");
    o
}
pub fn dart(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by otter-sync. Do not edit.\nimport 'dart:convert';\nimport 'package:otter_sync/otter_sync.dart';\nclass Present<T> { final T value; const Present(this.value); }\n",
    );
    writeln!(
        o,
        "final Map<String,dynamic> schema = jsonDecode(r'''{}''') as Map<String,dynamic>;",
        v["schema"]
    )
    .unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "enum {} {{ {} }}",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.as_str().unwrap())
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for suffix in ["", "Identity", "Patch"] {
            let fields: Vec<_> = arr(m, "fields")
                .iter()
                .filter(|f| {
                    let id = arr(m, "identity").contains(&f["name"]);
                    suffix.is_empty() || (suffix == "Identity" && id) || (suffix == "Patch" && !id)
                })
                .collect();
            let patch = suffix == "Patch";
            writeln!(o, "class {n}{suffix} {{").unwrap();
            for f in &fields {
                writeln!(
                    o,
                    " final {} {};",
                    if patch {
                        format!("Present<{}>?", ft(f, true))
                    } else {
                        ft(f, true)
                    },
                    s(f, "name")
                )
                .unwrap();
            }
            writeln!(
                o,
                " const {n}{suffix}({});",
                if fields.is_empty() {
                    String::new()
                } else {
                    format!(
                        "{{{}}}",
                        fields
                            .iter()
                            .map(|f| format!(
                                "{}this.{}",
                                if patch { "" } else { "required " },
                                s(f, "name")
                            ))
                            .collect::<Vec<_>>()
                            .join(",")
                    )
                }
            )
            .unwrap();
            writeln!(o, " Map<String,dynamic> toRecord() => {{").unwrap();
            for f in &fields {
                let k = s(f, "name");
                let x = if patch {
                    format!("{k}!.value")
                } else {
                    k.into()
                };
                writeln!(
                    o,
                    " {}'{k}': {},",
                    if patch {
                        format!("if ({k} != null) ")
                    } else {
                        String::new()
                    },
                    enc(f, &x, true)
                )
                .unwrap();
            }
            o.push_str(" };\n");
            if !patch {
                writeln!(
                    o,
                    " factory {n}{suffix}.fromRecord(Map<String,dynamic> row) => {n}{suffix}("
                )
                .unwrap();
                for f in &fields {
                    let k = s(f, "name");
                    let x = format!("row['{k}']");
                    let d = decode(&f["type"], &x, true);
                    writeln!(
                        o,
                        " {k}: {},",
                        if f["nullable"] == true {
                            format!("{x} == null ? null : {d}")
                        } else {
                            d
                        }
                    )
                    .unwrap();
                }
                o.push_str(" );\n");
            }
            if suffix.is_empty() {
                writeln!(
                    o,
                    " {n}Identity get identity => {n}Identity({});",
                    arr(m, "identity")
                        .iter()
                        .map(|x| format!("{0}: {0}", x.as_str().unwrap()))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        let mut params = vec![];
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let base = if op == "update" {
                let mut chars = key.chars();
                let slot_type =
                    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str());
                let input = format!("{n}{slot_type}Update");
                let m = arr(&v["schema"], "models")
                    .iter()
                    .find(|m| m["name"] == model)
                    .unwrap();
                let fields: Vec<_> = arr(m, "fields")
                    .iter()
                    .filter(|f| {
                        !arr(m, "identity").contains(&f["name"])
                            && slot["allowedPatchFields"]
                                .as_array()
                                .is_none_or(|a| a.contains(&f["name"]))
                    })
                    .collect();
                writeln!(o, "class {input} {{\n final {model}Identity identity;").unwrap();
                for f in &fields {
                    writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
                }
                writeln!(
                    o,
                    " const {input}({{required this.identity,{}}});",
                    fields
                        .iter()
                        .map(|f| format!("this.{}", s(f, "name")))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
                o.push_str(" Map<String,dynamic> toRecord() => {\n");
                for f in fields {
                    let k = s(f, "name");
                    writeln!(
                        o,
                        " if ({k} != null) '{k}': {},",
                        enc(f, &format!("{k}!.value"), true)
                    )
                    .unwrap();
                }
                o.push_str(" };\n}\n");
                input
            } else if op == "delete" {
                format!("{model}Identity")
            } else {
                model.to_string()
            };
            let card = s(slot, "cardinality");
            params.push(if card == "list" {
                format!("required List<{base}> {key}")
            } else if card == "optional" {
                format!("{base}? {key}")
            } else {
                format!("required {base} {key}")
            });
        }
        writeln!(
            o,
            "Map<String,dynamic> {}({{{}}}) {{ final operations=<Map<String,dynamic>>[];",
            lower(n),
            params.join(",")
        )
        .unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            let vals = if card == "list" {
                key.to_string()
            } else if card == "optional" {
                format!("[{key}].nonNulls")
            } else {
                format!("[{key}]")
            };
            let identity = if op == "delete" {
                "value.toRecord()"
            } else {
                "value.identity.toRecord()"
            };
            writeln!(o, " for (final value in {vals}) {{").unwrap();
            if op == "create" {
                writeln!(o," final state=value.toRecord(); for (final key in value.identity.toRecord().keys) {{ state.remove(key); }}").unwrap();
            }
            writeln!(
                o,
                " operations.add({{'model':'{model}','op':'{op}','identity':{identity}{}}}); }}",
                if op == "delete" {
                    String::new()
                } else if op == "create" {
                    ",'values':state".into()
                } else {
                    ",'values':value.toRecord()".into()
                }
            )
            .unwrap();
        }
        writeln!(
            o,
            " return {{'name':'{n}','version':{},'operations':operations}}; }}",
            mu["version"]
        )
        .unwrap();
    }
    dart_query_types(v, &mut o);
    o.push_str("class GeneratedClient { final Client client; GeneratedClient(this.client);\n");
    dart_queries(v, &mut o);
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        writeln!(o," Future<{n}?> read{n}({n}Identity identity) async {{ final row=await client.read('{n}',identity.toRecord()); return row == null ? null : {n}.fromRecord(row); }}\n Future<List<{n}>> {}({{Map<String,dynamic> where=const {{}}}}) async => (await client.query('{n}',where:where)).map({n}.fromRecord).toList();",lower(n)).unwrap();
    }
    o.push_str(
        " Future<int> mutate(Map<String,dynamic> mutation) => client.mutate(mutation);\n}\n",
    );
    o
}
fn upper(name: &str) -> String {
    let mut chars = name.chars();
    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str())
}
fn ts_queries(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let scalar = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let scalar = if scalar.is_empty() {
            "never".into()
        } else {
            scalar
        };
        let lists = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "list")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let filter = if lists.is_empty() {
            format!("Partial<{n}>")
        } else {
            format!("Partial<Omit<{n}, {lists}>>")
        };
        writeln!(o," async query{n}(options:{{where?:{filter};orderBy?:{{field:{scalar};direction:'ascending'|'descending'}}[];limit?:number}}={{}}):Promise<{n}[]> {{ if(!this.client.querySpec)throw Error('query capability unavailable'); return (await this.client.querySpec('{n}',{{filter:encode{n}Where(options.where??{{}}),orderBy:options.orderBy??[],...(options.limit===undefined?{{}}:{{limit:options.limit}})}})).map(decode{n}); }}").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o," async {}{}(identity:{n}Identity):Promise<{target}|null> {{ if(!this.client.related)throw Error('relation capability unavailable'); const row=await this.client.related('{n}',encode{n}Identity(identity),'{name}'); return row===null?null:decode{target}(row); }}",lower(n),upper(name)).unwrap();
        }
    }
    for inverse in arr(v, "inverses") {
        let n = s(inverse, "model");
        let target = s(inverse, "target");
        let name = s(inverse, "name");
        let reference = s(inverse, "reference");
        if inverse["list"] != true {
            writeln!(o," async {}{}(identity:{n}Identity):Promise<{target}|null> {{ if(!this.client.referencing)throw Error('inverse capability unavailable');const rows=await this.client.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}');if(rows.length>1)throw Error('singular inverse has multiple rows');return rows.length===0?null:decode{target}(rows[0]!); }}",lower(n),upper(name)).unwrap();
            continue;
        }
        writeln!(o," async {}{}(identity:{n}Identity):Promise<{target}[]> {{ if(!this.client.referencing)throw Error('inverse capability unavailable'); return (await this.client.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}')).map(decode{target}); }}",lower(n),upper(name)).unwrap();
    }
}
fn dart_query_types(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let fields = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] != "list")
            .collect::<Vec<_>>();
        writeln!(o, "class {n}Filter {{").unwrap();
        for f in &fields {
            writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
        }
        writeln!(
            o,
            " const {n}Filter({{{}}});\n Map<String,dynamic> toRecord()=>{{",
            fields
                .iter()
                .map(|f| format!("this.{}", s(f, "name")))
                .collect::<Vec<_>>()
                .join(",")
        )
        .unwrap();
        for f in &fields {
            let name = s(f, "name");
            writeln!(
                o,
                " if({name}!=null)'{name}':{},",
                enc(f, &format!("{name}!.value"), true)
            )
            .unwrap();
        }
        o.push_str("};\n}\n");
        let scalar = fields
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("by{}('{}')", upper(s(f, "name")), s(f, "name")))
            .collect::<Vec<_>>()
            .join(",");
        writeln!(o,"enum {n}OrderField {{{scalar}; final String wireName; const {n}OrderField(this.wireName);}}\nclass {n}Order {{ final {n}OrderField field; final bool descending; const {n}Order(this.field,{{this.descending=false}}); Map<String,dynamic> toRecord()=>{{'field':field.wireName,'direction':descending?'descending':'ascending'}}; }}").unwrap();
    }
}
fn dart_queries(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(o," Future<List<{n}>> query{n}({{{n}Filter? where,List<{n}Order> orderBy=const [],int? limit}}) async => (await client.querySpec('{n}',{{'filter':where?.toRecord()??{{}},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit}})).map({n}.fromRecord).toList();").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o," Future<{target}?> {}{}({n}Identity identity) async {{ final row=await client.related('{n}',identity.toRecord(),'{name}');return row==null?null:{target}.fromRecord(row); }}",lower(n),upper(name)).unwrap();
        }
    }
    for inverse in arr(v, "inverses") {
        let n = s(inverse, "model");
        let target = s(inverse, "target");
        let name = s(inverse, "name");
        let reference = s(inverse, "reference");
        if inverse["list"] != true {
            writeln!(o," Future<{target}?> {}{}({n}Identity identity) async {{final rows=await client.referencing('{n}',identity.toRecord(),'{target}','{reference}');if(rows.length>1)throw StateError('singular inverse has multiple rows');return rows.isEmpty?null:{target}.fromRecord(rows.single);}}",lower(n),upper(name)).unwrap();
            continue;
        }
        writeln!(o," Future<List<{target}>> {}{}({n}Identity identity) async => (await client.referencing('{n}',identity.toRecord(),'{target}','{reference}')).map({target}.fromRecord).toList();",lower(n),upper(name)).unwrap();
    }
}
