use serde_json::Value;
use std::fmt::Write;
fn arr<'a>(v: &'a Value, k: &str) -> &'a Vec<Value> {
    v[k].as_array().unwrap()
}
fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v[k].as_str().unwrap()
}
fn lower(s: &str) -> String {
    let mut c = s.chars();
    format!("{}{}", c.next().unwrap().to_lowercase(), c.as_str())
}
fn ty(t: &Value, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = ty(&t["element"], dart);
        return if dart {
            format!("List<{e}>")
        } else {
            format!("{e}[]")
        };
    }
    if t["kind"] == "enum" {
        return s(t, "name").into();
    }
    match s(t, "name") {
        "boolean" => {
            if dart {
                "bool"
            } else {
                "boolean"
            }
        }
        "int" => {
            if dart {
                "int"
            } else {
                "number"
            }
        }
        "float" => {
            if dart {
                "double"
            } else {
                "number"
            }
        }
        "dateTime" => {
            if dart {
                "DateTime"
            } else {
                "Date"
            }
        }
        _ => {
            if dart {
                "String"
            } else {
                "string"
            }
        }
    }
    .into()
}
fn ft(f: &Value, dart: bool) -> String {
    format!(
        "{}{}",
        ty(&f["type"], dart),
        if f["nullable"] == true {
            if dart { "?" } else { " | null" }
        } else {
            ""
        }
    )
}
fn decode(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = decode(&t["element"], "e", dart);
        return if dart {
            format!("({x} as List).map((e) => {e}).toList()")
        } else {
            format!("({x} as unknown[]).map(e => {e})")
        };
    }
    if t["kind"] == "enum" {
        let n = s(t, "name");
        return if dart {
            format!("{n}.values.byName({x} as String)")
        } else {
            format!("{x} as {n}")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("DateTime.parse({x} as String)")
        } else {
            format!("new Date({x} as string)")
        };
    }
    if dart && t["name"] == "float" {
        format!("({x} as num).toDouble()")
    } else {
        format!("{x} as {}", ty(t, dart))
    }
}
fn encoded(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = encoded(&t["element"], "e", dart);
        return if dart {
            format!("{x}.map((e) => {e}).toList()")
        } else {
            format!("{x}.map(e => {e})")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("{x}.toUtc().toIso8601String()")
        } else {
            format!("{x}.toISOString()")
        };
    }
    if dart && t["kind"] == "enum" {
        format!("{x}.name")
    } else {
        x.into()
    }
}
fn enc(f: &Value, x: &str, dart: bool) -> String {
    let e = encoded(
        &f["type"],
        &if dart && f["nullable"] == true {
            format!("{x}!")
        } else {
            x.into()
        },
        dart,
    );
    if f["nullable"] == true {
        format!("{x} == null ? null : {e}")
    } else {
        e
    }
}
pub fn typescript(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by ahead. Do not edit.\nexport interface ReadPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; querySpec(model:string,query:object):Promise<Record<string,unknown>[]>; related(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }\nexport interface WritePort extends ReadPort { mutate(value:object):Promise<number>; direct(operation:object):Promise<void>; }\nexport interface LivePort extends ReadPort { watch(model:string,where:Record<string,unknown>,listener:(rows:Record<string,unknown>[])=>void,onError?:(error:unknown)=>void):()=>void; }\n",
    );
    writeln!(o, "export const schema = {} as const;", v["schema"]).unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "export type {} = {};",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for (suffix, filter, partial) in
            [("", 0, false), ("Identity", 1, false), ("Patch", 2, true)]
        {
            writeln!(o, "export interface {n}{suffix} {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (filter == 1 && !id) || (filter == 2 && id) {
                    continue;
                }
                writeln!(
                    o,
                    " {}{}: {};",
                    s(f, "name"),
                    if partial { "?" } else { "" },
                    ft(f, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
        writeln!(
            o,
            "export function decode{n}(row:Record<string,unknown>):{n} {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            let k = s(f, "name");
            let x = format!("row.{k}");
            let dec = decode(&f["type"], &x, false);
            writeln!(
                o,
                " {k}: {},",
                if f["nullable"] == true {
                    format!("{x} == null ? null : {dec}")
                } else {
                    dec
                }
            )
            .unwrap();
        }
        o.push_str("}; }\n");
        for (suffix, partial) in [
            ("", false),
            ("Identity", false),
            ("Patch", true),
            ("Where", true),
        ] {
            let input = if suffix == "Where" {
                format!("Partial<{n}>")
            } else {
                format!("{n}{suffix}")
            };
            writeln!(o,"export function encode{n}{suffix}(value:{input}):Record<string,unknown> {{ return {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (suffix == "Identity" && !id) || (suffix == "Patch" && id) {
                    continue;
                }
                let k = s(f, "name");
                let ex = enc(f, &format!("value.{k}"), false);
                if partial {
                    writeln!(o, " ...(value.{k} !== undefined ? {{ {k}: {ex} }} : {{}}),").unwrap()
                } else {
                    writeln!(o, " {k}: {ex},").unwrap()
                }
            }
            o.push_str("}; }\n");
        }
    }
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(o, "export interface {n}Args {{").unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let input = match s(slot, "operation") {
                "create" => model.to_string(),
                "delete" => format!("{model}Identity"),
                _ => {
                    let patch = if let Some(a) = slot["allowedPatchFields"].as_array() {
                        format!(
                            "Pick<{model}Patch, {}>",
                            if a.is_empty() {
                                "never".into()
                            } else {
                                a.iter()
                                    .map(Value::to_string)
                                    .collect::<Vec<_>>()
                                    .join(" | ")
                            }
                        )
                    } else {
                        format!("{model}Patch")
                    };
                    format!("{{ identity:{model}Identity; values:{patch} }}")
                }
            };
            let card = s(slot, "cardinality");
            writeln!(
                o,
                " {}{}: {}{};",
                s(slot, "name"),
                if card == "optional" { "?" } else { "" },
                input,
                if card == "list" { "[]" } else { "" }
            )
            .unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "export function {n}(args:{n}Args) {{ const operations:object[] = [];"
        )
        .unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            writeln!(
                o,
                " for (const value of {}) {{",
                if card == "list" {
                    format!("args.{key}")
                } else if card == "optional" {
                    format!("args.{key} === undefined ? [] : [args.{key}]")
                } else {
                    format!("[args.{key}]")
                }
            )
            .unwrap();
            let id = if op == "update" {
                "value.identity"
            } else {
                "value"
            };
            let vals = if op == "delete" {
                String::new()
            } else if op == "update" {
                format!(", values:encode{model}Patch(value.values)")
            } else {
                format!(", values:encode{model}Patch(value)")
            };
            writeln!(o," operations.push({{ model:'{model}', op:'{op}', identity:encode{model}Identity({id}){vals} }}); }}").unwrap();
        }
        writeln!(
            o,
            " return {{name:'{n}',version:{},operations}}; }}",
            mu["version"]
        )
        .unwrap();
    }
    ts_models(v, &mut o);
    o.push_str("export class Mutate { readonly port:WritePort; constructor(port:WritePort) { this.port=port; }\n");
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(
            o,
            " {}(args:{n}Args):Promise<number> {{ return this.port.mutate({n}(args)); }}",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\n");
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "LivePort"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "export interface {suffix}Models {{ {} }}",
            names
                .iter()
                .map(|(key, n)| format!("{key}:{n}{suffix}Model;"))
                .collect::<Vec<_>>()
                .join(" ")
        )
        .unwrap();
        writeln!(
            o,
            "export function {}Models(port:{port}):{suffix}Models {{ return {{ {} }}; }}",
            lower(suffix),
            names
                .iter()
                .map(|(key, n)| format!("{key}:new {n}{suffix}Model(port)"))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    o.push_str("export class GeneratedTransaction { readonly transaction:WritePort; readonly models:TxModels; readonly mutate:Mutate; constructor(transaction:WritePort) { this.transaction=transaction; this.models=txModels(transaction); this.mutate=new Mutate(transaction); } }\n");
    o
}
fn slot_input_type(slot: &Value) -> String {
    let model = s(slot, "model");
    let one = match s(slot, "operation") {
        "create" => model.to_string(),
        "delete" => format!("{{ identity: {model}Identity }}"),
        _ => {
            let patch = match slot["allowedPatchFields"].as_array() {
                Some(a) if a.is_empty() => format!("Pick<{model}Patch, never>"),
                Some(a) => format!(
                    "Pick<{model}Patch, {}>",
                    a.iter()
                        .map(Value::to_string)
                        .collect::<Vec<_>>()
                        .join(" | ")
                ),
                None => format!("{model}Patch"),
            };
            format!("{{ identity: {model}Identity; patch: {patch} }}")
        }
    };
    match s(slot, "cardinality") {
        "list" => format!("{one}[]"),
        "optional" => format!("{one} | null"),
        _ => one,
    }
}
/// Client entry point bound to the compiled schema. `runtime` is the import specifier of `@ahead/client`.
pub fn client_typescript(runtime: &str) -> String {
    let mut o = String::from("// Generated by ahead. Do not edit.\n");
    writeln!(o, "import {{ Client, type Connection, type ConnectionOptions, type RecordValue, type Transport }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ httpTransport, type Connection, type ConnectionOptions, type Transport }} from \"{runtime}\";").unwrap();
    o.push_str("import { schema, liveModels, GeneratedTransaction, type LiveModels } from \"./generated.ts\";\n");
    o.push_str("export * from \"./generated.ts\";\n");
    o.push_str("export class Channels { readonly #client: Client;\n constructor(client: Client) { this.#client = client; }\n subscribe(channel: string) { return this.#client.subscribe(channel); }\n unsubscribe(channel: string) { return this.#client.unsubscribe(channel); }\n}\n");
    o.push_str("export class GeneratedClient {\n");
    o.push_str(" readonly client: Client;\n readonly connection: Connection | undefined;\n readonly models: LiveModels;\n readonly channels: Channels;\n");
    o.push_str(" private constructor(client: Client, connection: Connection | undefined) { this.client = client; this.connection = connection; this.models = liveModels(client); this.channels = new Channels(client); }\n");
    o.push_str(" /** Opens the local database at `path`. With a transport, the connection starts immediately and retries on its own. */\n");
    o.push_str(" static async open(options: { path: string; transport?: Transport; connection?: ConnectionOptions; migration?: { defaults?: RecordValue; replayPull?: boolean } }): Promise<GeneratedClient> {\n");
    o.push_str("  const client = await Client.open({ path: options.path, schema, ...(options.migration === undefined ? {} : { migration: options.migration }) });\n");
    o.push_str("  const connection = options.transport === undefined ? undefined : await client.connect(options.transport, options.connection ?? {});\n");
    o.push_str("  return new GeneratedClient(client, connection);\n }\n");
    o.push_str(" transaction<T>(body: (tx: GeneratedTransaction) => Promise<T>): Promise<T> { return this.client.transaction((tx) => body(new GeneratedTransaction(tx))); }\n");
    o.push_str(" status() { return this.client.status(); }\n");
    o.push_str(" close() { return this.client.close(); }\n");
    o.push_str("}\n");
    o
}
/// Backend surface bound to the compiled schema. `runtime` is the import specifier of `@ahead/server`.
pub fn backend_typescript(v: &Value, runtime: &str) -> String {
    let mut o = String::from("// Generated by ahead. Do not edit.\n");
    writeln!(o, "import {{ createBackend as createRuntimeBackend, type BackendOptions, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ MutationRejected, devAuth, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    let models = arr(&v["schema"], "models");
    let names: Vec<String> = models
        .iter()
        .flat_map(|m| {
            let n = s(m, "name");
            [
                format!("{n} as {n}Record"),
                format!("{n}Identity"),
                format!("{n}Patch"),
            ]
        })
        .collect();
    writeln!(
        o,
        "import type {{ {} }} from \"./generated.ts\";",
        names.join(", ")
    )
    .unwrap();
    for m in models {
        let n = s(m, "name");
        writeln!(o, "export type {n} = {n}Record;").unwrap();
        writeln!(o, "export type {{ {n}Identity, {n}Patch }};").unwrap();
        writeln!(o, "export function {n}(identity: {n}Identity): RecordRef {{ return {{ model: \"{n}\", identity }}; }}").unwrap();
    }
    let mut backend = v.clone();
    if let Some(history) = v.get("backendMutations") {
        backend["mutations"] = history.clone();
        backend.as_object_mut().unwrap().remove("backendMutations");
    }
    writeln!(o, "const schema = {} as const;", backend).unwrap();
    let mutations = arr(&backend, "mutations");
    let latest = |name: &str| {
        mutations
            .iter()
            .filter(|m| s(m, "name") == name)
            .map(|m| m["version"].as_u64().unwrap())
            .max()
            .unwrap()
    };
    let key = |m: &Value| {
        let n = s(m, "name");
        let ver = m["version"].as_u64().unwrap();
        if ver == latest(n) {
            lower(n)
        } else {
            format!("{}V{ver}", lower(n))
        }
    };
    let input_name = |m: &Value| {
        let n = s(m, "name");
        let ver = m["version"].as_u64().unwrap();
        if ver == latest(n) {
            format!("{n}Input")
        } else {
            format!("{n}V{ver}Input")
        }
    };
    for m in mutations {
        writeln!(o, "export interface {} {{", input_name(m)).unwrap();
        for slot in arr(m, "slots") {
            writeln!(o, " {}: {};", s(slot, "name"), slot_input_type(slot)).unwrap();
        }
        o.push_str("}\n");
    }
    o.push_str("export interface Handlers<Tx> {\n");
    for m in mutations {
        writeln!(
            o,
            " {}(call: HandlerCall<Tx, {}>): Promise<void | {{ channel: string }}>;",
            key(m),
            input_name(m)
        )
        .unwrap();
    }
    o.push_str("}\n");
    o.push_str("export interface Loaders<Tx> {\n");
    for m in models {
        let n = s(m, "name");
        writeln!(
            o,
            " {}(call: LoaderCall<Tx, {n}Identity>): Promise<readonly ({n} | null)[]>;",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\n");
    o.push_str("export type Options<Tx> = Omit<BackendOptions<Tx>, \"config\" | \"handlers\" | \"loaders\"> & { handlers: Handlers<Tx>; loaders: Loaders<Tx> };\n");
    o.push_str("export function createBackend<Tx>(options: Options<Tx>) {\n return createRuntimeBackend<Tx>({ ...options, config: schema, handlers: options.handlers as unknown as BackendOptions<Tx>[\"handlers\"], loaders: options.loaders as unknown as BackendOptions<Tx>[\"loaders\"] });\n}\n");
    o
}
pub fn dart(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by ahead. Do not edit.\nimport 'dart:convert';\nimport 'package:ahead/ahead.dart';\nclass Present<T> { final T value; const Present(this.value); }\n",
    );
    writeln!(
        o,
        "final Map<String,dynamic> schema = jsonDecode(r'''{}''') as Map<String,dynamic>;",
        v["schema"]
    )
    .unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "enum {} {{ {} }}",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.as_str().unwrap())
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for suffix in ["", "Identity", "Patch"] {
            let fields: Vec<_> = arr(m, "fields")
                .iter()
                .filter(|f| {
                    let id = arr(m, "identity").contains(&f["name"]);
                    suffix.is_empty() || (suffix == "Identity" && id) || (suffix == "Patch" && !id)
                })
                .collect();
            let patch = suffix == "Patch";
            writeln!(o, "class {n}{suffix} {{").unwrap();
            for f in &fields {
                writeln!(
                    o,
                    " final {} {};",
                    if patch {
                        format!("Present<{}>?", ft(f, true))
                    } else {
                        ft(f, true)
                    },
                    s(f, "name")
                )
                .unwrap();
            }
            writeln!(
                o,
                " const {n}{suffix}({});",
                if fields.is_empty() {
                    String::new()
                } else {
                    format!(
                        "{{{}}}",
                        fields
                            .iter()
                            .map(|f| format!(
                                "{}this.{}",
                                if patch { "" } else { "required " },
                                s(f, "name")
                            ))
                            .collect::<Vec<_>>()
                            .join(",")
                    )
                }
            )
            .unwrap();
            writeln!(o, " Map<String,dynamic> toRecord() => {{").unwrap();
            for f in &fields {
                let k = s(f, "name");
                let x = if patch {
                    format!("{k}!.value")
                } else {
                    k.into()
                };
                writeln!(
                    o,
                    " {}'{k}': {},",
                    if patch {
                        format!("if ({k} != null) ")
                    } else {
                        String::new()
                    },
                    enc(f, &x, true)
                )
                .unwrap();
            }
            o.push_str(" };\n");
            if !patch {
                writeln!(
                    o,
                    " factory {n}{suffix}.fromRecord(Map<String,dynamic> row) => {n}{suffix}("
                )
                .unwrap();
                for f in &fields {
                    let k = s(f, "name");
                    let x = format!("row['{k}']");
                    let d = decode(&f["type"], &x, true);
                    writeln!(
                        o,
                        " {k}: {},",
                        if f["nullable"] == true {
                            format!("{x} == null ? null : {d}")
                        } else {
                            d
                        }
                    )
                    .unwrap();
                }
                o.push_str(" );\n");
            }
            if suffix.is_empty() {
                writeln!(
                    o,
                    " {n}Identity get identity => {n}Identity({});",
                    arr(m, "identity")
                        .iter()
                        .map(|x| format!("{0}: {0}", x.as_str().unwrap()))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    let mut mutate_methods = vec![];
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        let mut params = vec![];
        let mut keys = vec![];
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            keys.push(key);
            let op = s(slot, "operation");
            let base = if op == "update" {
                let mut chars = key.chars();
                let slot_type =
                    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str());
                let input = format!("{n}{slot_type}Update");
                let m = arr(&v["schema"], "models")
                    .iter()
                    .find(|m| m["name"] == model)
                    .unwrap();
                let fields: Vec<_> = arr(m, "fields")
                    .iter()
                    .filter(|f| {
                        !arr(m, "identity").contains(&f["name"])
                            && slot["allowedPatchFields"]
                                .as_array()
                                .is_none_or(|a| a.contains(&f["name"]))
                    })
                    .collect();
                writeln!(o, "class {input} {{\n final {model}Identity identity;").unwrap();
                for f in &fields {
                    writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
                }
                writeln!(
                    o,
                    " const {input}({{required this.identity,{}}});",
                    fields
                        .iter()
                        .map(|f| format!("this.{}", s(f, "name")))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
                o.push_str(" Map<String,dynamic> toRecord() => {\n");
                for f in fields {
                    let k = s(f, "name");
                    writeln!(
                        o,
                        " if ({k} != null) '{k}': {},",
                        enc(f, &format!("{k}!.value"), true)
                    )
                    .unwrap();
                }
                o.push_str(" };\n}\n");
                input
            } else if op == "delete" {
                format!("{model}Identity")
            } else {
                model.to_string()
            };
            let card = s(slot, "cardinality");
            params.push(if card == "list" {
                format!("required List<{base}> {key}")
            } else if card == "optional" {
                format!("{base}? {key}")
            } else {
                format!("required {base} {key}")
            });
        }
        writeln!(
            o,
            "Map<String,dynamic> {}({{{}}}) {{ final operations=<Map<String,dynamic>>[];",
            lower(n),
            params.join(",")
        )
        .unwrap();
        mutate_methods.push(format!(
            " Future<int> {0}({{{1}}}) => port.mutate(_{0}({2}));",
            lower(n),
            params.join(","),
            keys.iter()
                .map(|k| format!("{k}:{k}"))
                .collect::<Vec<_>>()
                .join(",")
        ));
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            let vals = if card == "list" {
                key.to_string()
            } else if card == "optional" {
                format!("[{key}].nonNulls")
            } else {
                format!("[{key}]")
            };
            let identity = if op == "delete" {
                "value.toRecord()"
            } else {
                "value.identity.toRecord()"
            };
            writeln!(o, " for (final value in {vals}) {{").unwrap();
            if op == "create" {
                writeln!(o," final state=value.toRecord(); for (final key in value.identity.toRecord().keys) {{ state.remove(key); }}").unwrap();
            }
            writeln!(
                o,
                " operations.add({{'model':'{model}','op':'{op}','identity':{identity}{}}}); }}",
                if op == "delete" {
                    String::new()
                } else if op == "create" {
                    ",'values':state".into()
                } else {
                    ",'values':value.toRecord()".into()
                }
            )
            .unwrap();
        }
        writeln!(
            o,
            " return {{'name':'{n}','version':{},'operations':operations}}; }}\nfinal _{} = {};",
            mu["version"],
            lower(n),
            lower(n)
        )
        .unwrap();
    }
    dart_query_types(v, &mut o);
    dart_models(v, &mut o);
    writeln!(
        o,
        "class Mutate {{ final WritePort port; Mutate(this.port);\n{}\n}}",
        mutate_methods.join("\n")
    )
    .unwrap();
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "Client"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "class {suffix}Models {{ final {port} port; {suffix}Models(this.port);\n{}\n}}",
            names
                .iter()
                .map(|(key, n)| format!(
                    " late final {n}{suffix}Model {key} = {n}{suffix}Model(port);"
                ))
                .collect::<Vec<_>>()
                .join("\n")
        )
        .unwrap();
    }
    o.push_str("class Channels { final Client client; Channels(this.client);\n Future<void> subscribe(String channel) => client.subscribe(channel);\n Future<void> unsubscribe(String channel) => client.unsubscribe(channel);\n}\n");
    o.push_str("class GeneratedTransaction { final Transaction transaction; late final TxModels models = TxModels(transaction); late final Mutate mutate = Mutate(transaction); GeneratedTransaction(this.transaction); }\n");
    o.push_str("class GeneratedClient { final Client client; final RuntimeConnection? connection; late final LiveModels models = LiveModels(client); late final Channels channels = Channels(client);\n GeneratedClient._(this.client, this.connection);\n");
    o.push_str(" /// Opens the local database at [path]. With a [transport], the connection starts immediately and retries on its own.\n");
    o.push_str(" static Future<GeneratedClient> open({required String path, Transport? transport, String? libraryPath, Map<String,dynamic>? migration, void Function(Object)? onError, Future<void> Function()? refreshAuth}) async {\n  final client = await Client.open(path:path, schema:schema, libraryPath:libraryPath, migration:migration);\n  final connection = transport == null ? null : await client.connect(transport, onError:onError, refreshAuth:refreshAuth);\n  return GeneratedClient._(client, connection);\n }\n");
    o.push_str(" Future<T> transaction<T>(Future<T> Function(GeneratedTransaction tx) body) => client.transaction((tx) => body(GeneratedTransaction(tx)));\n Future<Map<String,dynamic>> status() => client.status();\n Future<void> close() => client.close();\n}\n");
    o
}
fn upper(name: &str) -> String {
    let mut chars = name.chars();
    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str())
}
fn ts_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let scalar = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let scalar = if scalar.is_empty() {
            "never".into()
        } else {
            scalar
        };
        let lists = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "list")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let filter = if lists.is_empty() {
            format!("Partial<{n}>")
        } else {
            format!("Partial<Omit<{n}, {lists}>>")
        };
        writeln!(
            o,
            "export class {n}Model {{ readonly port:ReadPort; constructor(port:ReadPort) {{ this.port=port; }}"
        )
        .unwrap();
        writeln!(o, " async get(identity:{n}Identity):Promise<{n}|null> {{ const row=await this.port.read('{n}',encode{n}Identity(identity)); return row===null ? null : decode{n}(row); }}").unwrap();
        writeln!(o, " async query(options:{{where?:{filter};orderBy?:{{field:{scalar};direction:'ascending'|'descending'}}[];limit?:number}}={{}}):Promise<{n}[]> {{ return (await this.port.querySpec('{n}',{{filter:encode{n}Where(options.where??{{}}),orderBy:options.orderBy??[],...(options.limit===undefined?{{}}:{{limit:options.limit}})}})).map(decode{n}); }}").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const row=await this.port.related('{n}',encode{n}Identity(identity),'{name}'); return row===null?null:decode{target}(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const rows=await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}');if(rows.length>1)throw Error('singular inverse has multiple rows');return rows.length===0?null:decode{target}(rows[0]!); }}").unwrap();
            } else {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}[]> {{ return (await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}')).map(decode{target}); }}").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "export class {n}LiveModel extends {n}Model {{ declare readonly port:LivePort; constructor(port:LivePort) {{ super(port); }}\n watch(options:{{where?:{filter}}}, listener:(rows:{n}[])=>void, onError?:(error:unknown)=>void):()=>void {{ return this.port.watch('{n}',encode{n}Where(options.where??{{}}),(rows)=>listener(rows.map(decode{n})),onError); }}\n}}").unwrap();
        writeln!(o, "export class {n}TxModel extends {n}Model {{ declare readonly port:WritePort; constructor(port:WritePort) {{ super(port); }}\n create(value:{n}):Promise<void> {{ return this.port.direct({{model:'{n}',op:'create',identity:encode{n}Identity(value),values:encode{n}Patch(value)}}); }}\n update(identity:{n}Identity, patch:{n}Patch):Promise<void> {{ return this.port.direct({{model:'{n}',op:'update',identity:encode{n}Identity(identity),values:encode{n}Patch(patch)}}); }}\n delete(identity:{n}Identity):Promise<void> {{ return this.port.direct({{model:'{n}',op:'delete',identity:encode{n}Identity(identity)}}); }}\n}}").unwrap();
    }
}
fn dart_query_types(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let fields = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] != "list")
            .collect::<Vec<_>>();
        writeln!(o, "class {n}Filter {{").unwrap();
        for f in &fields {
            writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
        }
        writeln!(
            o,
            " const {n}Filter({{{}}});\n Map<String,dynamic> toRecord()=>{{",
            fields
                .iter()
                .map(|f| format!("this.{}", s(f, "name")))
                .collect::<Vec<_>>()
                .join(",")
        )
        .unwrap();
        for f in &fields {
            let name = s(f, "name");
            writeln!(
                o,
                " if({name}!=null)'{name}':{},",
                enc(f, &format!("{name}!.value"), true)
            )
            .unwrap();
        }
        o.push_str("};\n}\n");
        let scalar = fields
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("by{}('{}')", upper(s(f, "name")), s(f, "name")))
            .collect::<Vec<_>>()
            .join(",");
        writeln!(o,"enum {n}OrderField {{{scalar}; final String wireName; const {n}OrderField(this.wireName);}}\nclass {n}Order {{ final {n}OrderField field; final bool descending; const {n}Order(this.field,{{this.descending=false}}); Map<String,dynamic> toRecord()=>{{'field':field.wireName,'direction':descending?'descending':'ascending'}}; }}").unwrap();
    }
}
fn dart_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(
            o,
            "class {n}Model {{ final ReadPort port; {n}Model(this.port);"
        )
        .unwrap();
        writeln!(o, " Future<{n}?> get({n}Identity identity) async {{ final row=await port.read('{n}',identity.toRecord()); return row == null ? null : {n}.fromRecord(row); }}").unwrap();
        writeln!(o, " Future<List<{n}>> query({{{n}Filter? where,List<{n}Order> orderBy=const [],int? limit}}) async => (await port.querySpec('{n}',{{'filter':where?.toRecord()??{{}},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit}})).map({n}.fromRecord).toList();").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{ final row=await port.related('{n}',identity.toRecord(),'{name}');return row==null?null:{target}.fromRecord(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{final rows=await port.referencing('{n}',identity.toRecord(),'{target}','{reference}');if(rows.length>1)throw StateError('singular inverse has multiple rows');return rows.isEmpty?null:{target}.fromRecord(rows.single);}}").unwrap();
            } else {
                writeln!(o, " Future<List<{target}>> {name}({n}Identity identity) async => (await port.referencing('{n}',identity.toRecord(),'{target}','{reference}')).map({target}.fromRecord).toList();").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "class {n}LiveModel extends {n}Model {{ final Client client; {n}LiveModel(this.client) : super(client);\n Stream<List<{n}>> watch({{{n}Filter? where}}) => client.watch('{n}', where:where?.toRecord()??{{}}).map((rows) => rows.map({n}.fromRecord).toList());\n}}").unwrap();
        writeln!(o, "class {n}TxModel extends {n}Model {{ final WritePort writer; {n}TxModel(this.writer) : super(writer);\n Future<void> create({n} value) {{ final state=value.toRecord(); for (final key in value.identity.toRecord().keys) {{ state.remove(key); }} return writer.direct({{'model':'{n}','op':'create','identity':value.identity.toRecord(),'values':state}}); }}\n Future<void> update({n}Identity identity, {n}Patch patch) => writer.direct({{'model':'{n}','op':'update','identity':identity.toRecord(),'values':patch.toRecord()}});\n Future<void> delete({n}Identity identity) => writer.direct({{'model':'{n}','op':'delete','identity':identity.toRecord()}});\n}}").unwrap();
    }
}
