import 'dart:convert';
import '../../mutation_history.dart';
import '../backend/backend_contract.dart';

final class BackendTypescriptEmission {
  const BackendTypescriptEmission({required this.backendContract});

  final String backendContract;

  Map<String, String> get files => {'backend_contract.ts': backendContract};
}

/// One file: the typed Model surface and the forwarders onto the product's
/// bindings. How that is served is the handwritten host's business, so nothing
/// generated stands a server up.
BackendTypescriptEmission emitBackendTypescript(
  BackendContract contract, {
  MutationHistory? history,
}) => BackendTypescriptEmission(
  backendContract: _emitContract(
    contract,
    history ?? MutationHistory.fromContract(contract),
  ),
);

String _emitContract(BackendContract contract, MutationHistory history) {
  final output = StringBuffer()
    ..writeln('// Generated by local_sync_compiler. Do not edit.')
    ..writeln()
    ..writeln('import type {')
    ..writeln('  BackendModelBinding,')
    ..writeln('  BackendReadContext,')
    ..writeln('  BackendWriteContext,')
    ..writeln('  GeneratedBackendContract,');
  if (contract.mutations.isNotEmpty) {
    output
      ..writeln('  GeneratedMutationContract,')
      ..writeln('  MutationSettlement,');
  }
  output
    ..writeln("} from 'local-sync-backend';")
    ..writeln();

  for (final model in contract.models) {
    _writeModelTypes(output, contract, model);
    _writeForwarders(output, model);
  }
  _writeBindings(output, contract);
  _writeGeneratedContract(output, contract);
  if (contract.mutations.isNotEmpty) {
    _writeCurrentModelOperations(output, contract);
    _writeVersionedMutations(output, history);
  }
  return '${output.toString().trimRight()}\n';
}

// Existing product helpers may name the current Model operation types. These
// exports remain current; retained mutation arguments never reference them.
void _writeCurrentModelOperations(
  StringBuffer output,
  BackendContract contract,
) {
  for (final model in contract.models) {
    output
      ..writeln('export type ${model.name}CreateOperation = Readonly<{')
      ..writeln('  identity: ${model.name}Identity;')
      ..writeln('  data: ${model.name}CreateData;')
      ..writeln('}>;')
      ..writeln()
      ..writeln('export type ${model.name}UpdateOperation = Readonly<{')
      ..writeln('  identity: ${model.name}Identity;')
      ..writeln('  patch: ${model.name}Patch;')
      ..writeln('}>;')
      ..writeln()
      ..writeln('export type ${model.name}DeleteOperation = Readonly<{')
      ..writeln('  identity: ${model.name}Identity;')
      ..writeln('}>;')
      ..writeln();
  }
}

void _writeVersionedMutations(StringBuffer output, MutationHistory history) {
  for (final entry in history.mutations.entries) {
    for (final version in entry.value.entries) {
      final descriptor = version.value as Map;
      final input = descriptor['input'] as Map;
      output.writeln(
        'export type ${entry.key}V${version.key}Arguments = Readonly<{',
      );
      for (final slot in descriptor['slots'] as List) {
        final model = (input['models'] as Map).values.cast<Map>().singleWhere(
          (m) => m['name'] == slot['model'],
        );
        final fields = (model['fields'] as List).cast<Map>();
        String object(Iterable<Map> selected, {bool patch = false}) =>
            'Readonly<{ ' +
            selected
                .map(
                  (f) =>
                      '${f['name']}${patch ? '?' : ''}: ${_inputType(f, input)};',
                )
                .join(' ') +
            ' }>';
        final identity = object(fields.where((f) => f['identity'] == true));
        final op = slot['operation'];
        var type = 'Readonly<{ identity: $identity;';
        if (op == 'create')
          type +=
              ' data: ${object(fields.where((f) => f['identity'] != true))};';
        if (op == 'update')
          type +=
              ' patch: ${object(fields.where((f) => (slot['allowedPatchFields'] as List).contains(f['name'])), patch: true)};';
        type += ' }>';
        if (slot['cardinality'] == 'list') type = 'readonly $type[]';
        if (slot['cardinality'] == 'optional') type = '$type | null';
        output.writeln('  ${slot['name']}: $type;');
      }
      output.writeln('}>;');
    }
    final latest = entry.value.keys
        .map(int.parse)
        .reduce((a, b) => a > b ? a : b);
    output.writeln(
      'export type ${entry.key}Arguments = ${entry.key}V${latest}Arguments;',
    );
  }
  output.writeln('export type GeneratedMutationArguments = Readonly<{');
  for (final entry in history.mutations.entries) {
    output.writeln('  ${_lowerCamel(entry.key)}: Readonly<{');
    for (final version in entry.value.keys)
      output.writeln('    v$version: ${entry.key}V${version}Arguments;');
    output.writeln('  }>;');
  }
  output.writeln('}>;');
  output.writeln(
    'export type LocalSyncMutations<TTx, TNames extends keyof GeneratedMutationArguments = keyof GeneratedMutationArguments> = Readonly<{',
  );
  output.writeln(
    '  [K in TNames]: Readonly<{ [V in keyof GeneratedMutationArguments[K]]: (context: BackendWriteContext<TTx>, arguments_: GeneratedMutationArguments[K][V]) => Promise<MutationSettlement | void> }>;',
  );
  output.writeln('}>;');
  for (final entry in history.mutations.entries) {
    final key = _lowerCamel(entry.key);
    for (final version in entry.value.keys) {
      output.writeln(
        "export function forward${entry.key}V$version<TTx>(resolver: LocalSyncMutations<TTx, '$key'>['$key']['v$version'], context: BackendWriteContext<TTx>, arguments_: ${entry.key}V${version}Arguments): Promise<MutationSettlement | void> {",
      );
      output.writeln('  return resolver(context, arguments_);');
      output.writeln('}');
    }
  }
  output.writeln('export const generatedMutations = { mutations: {');
  for (final entry in history.mutations.entries) {
    output.writeln('  ${_lowerCamel(entry.key)}: {');
    for (final version in entry.value.entries) {
      final json = jsonEncode(version.value);
      output.writeln(
        '    v${version.key}: {${json.substring(1, json.length - 1)}, forward: forward${entry.key}V${version.key}},',
      );
    }
    output.writeln('  },');
  }
  output.writeln('} } as const satisfies GeneratedMutationContract;');
}

String _inputType(Map field, Map input) {
  final type = field['type'] as Map;
  String scalar(String name) => switch (name) {
    'boolean' => 'boolean',
    'int' || 'float' => 'number',
    _ => 'string',
  };
  final base = switch (type['kind']) {
    'enum' =>
      (input['enumValues'][type['name']] as List)
          .map((v) => _quote(v as String))
          .join(' | '),
    'list' => 'readonly ${scalar(type['element'] as String)}[]',
    _ => scalar(type['name'] as String),
  };
  return field['nullable'] == true ? '$base | null' : base;
}

void _writeModelTypes(
  StringBuffer output,
  BackendContract contract,
  BackendModelContract model,
) {
  _writeObjectType(output, '${model.name}Identity', model.identity, contract);
  _writeObjectType(output, '${model.name}State', model.fields, contract);
  final mutable = _mutableFields(model);
  _writeObjectType(output, '${model.name}CreateData', mutable, contract);
  _writeObjectType(
    output,
    '${model.name}Patch',
    mutable,
    contract,
    optional: true,
  );
  output
    ..writeln(
      'export type ${model.name}BackendBinding<TTx> = BackendModelBinding<',
    )
    ..writeln('  TTx,')
    ..writeln('  ${model.name}Identity,')
    ..writeln('  ${model.name}State')
    ..writeln('>;')
    ..writeln();
}

void _writeObjectType(
  StringBuffer output,
  String name,
  List<BackendFieldContract> fields,
  BackendContract contract, {
  bool optional = false,
}) {
  output.writeln('export type $name = Readonly<{');
  for (final field in fields) {
    output.writeln(
      '  ${field.name}${optional ? '?' : ''}: '
      '${_typescriptType(field, contract)};',
    );
  }
  output
    ..writeln('}>;')
    ..writeln();
}

void _writeForwarders(StringBuffer output, BackendModelContract model) {
  final name = model.name;
  output
    ..writeln('export function forward${name}Read<TTx>(')
    ..writeln('  binding: ${name}BackendBinding<TTx>,')
    ..writeln('  context: BackendReadContext<TTx>,')
    ..writeln('  identities: readonly ${name}Identity[],')
    ..writeln('): Promise<readonly (${name}State | null)[]> {')
    ..writeln('  return binding.read.forViewer(context, identities);')
    ..writeln('}')
    ..writeln();
}

/// The Downlink surface, as the Backend's own choice (CAP-488).
///
/// Every key is optional and every key is exact: a Backend may register a
/// loader for any subset of the generated Models, but a name that is not one
/// of them, or a value whose identity/state types do not match, is a
/// TypeScript compile error. Registering nothing for a Model is how a Model
/// stays off the Downlink — there is no annotation for it any more.
void _writeBindings(StringBuffer output, BackendContract contract) {
  output.writeln('export type GeneratedBackendModelBindings<TTx> = Readonly<{');
  for (final model in contract.models) {
    output.writeln(
      '  ${_lowerCamel(model.name)}?: ${model.name}BackendBinding<TTx>;',
    );
  }
  output
    ..writeln('}>;')
    ..writeln();
}

void _writeGeneratedContract(StringBuffer output, BackendContract contract) {
  output
    ..writeln('export const generatedContract = {')
    ..writeln('  enumValues: {');
  for (final definition in contract.enums) {
    output.writeln(
      '    ${definition.name}: '
      '[${definition.values.map(_quote).join(', ')}],',
    );
  }
  output
    ..writeln('  },')
    ..writeln('  models: {');
  for (final model in contract.models) {
    final key = _lowerCamel(model.name);
    output
      ..writeln('    $key: {')
      ..writeln("      name: '${model.name}',")
      ..writeln(
        '      identityFields: [${model.identity.map((field) => _quote(field.name)).join(', ')}],',
      )
      ..writeln('      fields: [');
    final identityNames = model.identity.map((field) => field.name).toSet();
    for (final field in model.fields) {
      output.writeln(
        '        { name: ${_quote(field.name)}, nullable: ${field.nullable}, '
        'identity: ${identityNames.contains(field.name)}, '
        'type: ${_descriptorType(field.type)} },',
      );
    }
    output
      ..writeln('      ],')
      ..writeln('      forward: { read: forward${model.name}Read },')
      ..writeln('    },');
  }
  output
    ..writeln('  },')
    ..writeln('} as const satisfies GeneratedBackendContract;')
    ..writeln();
}

String _typescriptType(BackendFieldContract field, BackendContract contract) {
  final base = switch (field.type) {
    BackendScalarFieldType(:final scalar) => switch (scalar.name) {
      'boolean' => 'boolean',
      'int' || 'float' => 'number',
      _ => 'string',
    },
    BackendEnumFieldType(:final name) =>
      contract.enums
          .singleWhere((definition) => definition.name == name)
          .values
          .map(_quote)
          .join(' | '),
    BackendScalarListFieldType(:final element) => switch (element.name) {
      'boolean' => 'readonly boolean[]',
      'int' || 'float' => 'readonly number[]',
      _ => 'readonly string[]',
    },
  };
  return field.nullable ? '$base | null' : base;
}

String _descriptorType(BackendFieldType type) => switch (type) {
  BackendScalarFieldType(:final scalar) =>
    "{ kind: 'scalar', name: '${scalar.name}' }",
  BackendEnumFieldType(:final name) => "{ kind: 'enum', name: '$name' }",
  BackendScalarListFieldType(:final element) =>
    "{ kind: 'list', element: '${element.name}' }",
};

List<BackendFieldContract> _mutableFields(BackendModelContract model) {
  final identityNames = model.identity.map((field) => field.name).toSet();
  return [
    for (final field in model.fields)
      if (!identityNames.contains(field.name)) field,
  ];
}

String _lowerCamel(String value) =>
    value.isEmpty ? value : '${value[0].toLowerCase()}${value.substring(1)}';

String _quote(String value) =>
    "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
