[package]
name = "ahead-integration"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
ahead-core = { path = "../../crates/core" }
ahead-client = { path = "../../crates/client" }
ahead-server = { path = "../../crates/server" }
ahead-sqlite = { path = "../../crates/sqlite" }
serde_json.workspace = true
tempfile.workspace = true
