name: local_sync
description: Handwritten local Model storage and projection runtime.
publish_to: none

environment:
  sdk: ^3.10.3

dependencies:
  collection: ^1.19.0
  local_sync_database:
    path: ../local_sync_database
  meta: ^1.16.0
  uuid: ^4.5.3

dev_dependencies:
  local_sync_database_sqlite:
    path: ../local_sync_database_sqlite
  test: ^1.25.0
